parameters:
    youtube_api_key: "AIzaSyBmyFUjbgq4NCio7QxhyVBJGC8DO13QZTY"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Déclaration explicite du service YouTubeService
    App\Service\YouTubeService:
        arguments:
            $apiKey: '%youtube_api_key%'

    # Déclaration du contrôleur d'exception
    App\Controller\Other\ExceptionController:
        public: true
        tags: ['controller.service_arguments']
        arguments:
            $twig: '@twig'
            $kernel: '@kernel'
